name: CI

on: push

jobs:
  test-e2e:
    uses: jill64/playwright-config/.github/workflows/duplex-playwright.yml@0da2bf603718b869daea0654fad791e43c6ea777 # v2.2.3
    with:
      hosting-provider: cloudflare
